spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/escuela
    username: root
    password: bravo

# Propiedades para hibernate cree adecuadamente las instrucciones SQL
  jpa:
    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

server:
  port: 9000
