spring:
  application:
    name: servidor-gateway   
  cloud: 
   gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
              allowedOrigins: "*"
              allowedMethods: "*"
              allowedHeaders: "*"   
      routes:
      - id: servHoteles #Id de la ruta 
        uri: lb://servicio-hoteles
        predicates:
          - Path=/shoteles/** #Cuando Gateway detecte que en la peticion URL venga este path, enrutara la peticion hacia el servicio indicado en la propiedad "uri" (lb://servicio-hoteles)
        filters:
          - RewritePath=/shoteles/*, / #Lo que indica es que a la url indicada en la propiedad "uri", se le adicionará un "/" mas todo lo que venga despues de "shoteles" en la petición URL de entrada
          
      - id: servVuelos
        uri: lb://servicio-vuelos 
        predicates:
          - Path=/svuelos/**
        filters:
          - RewritePath=/svuelos/*, /      
          
      - id: servReservas
        uri: lb://servicio-reservas 
        predicates:
          - Path=/sreservas/**
        filters:
          - RewritePath=/sreservas/*, /
server:
  port: 9000
      
eureka:
  client:
    register-with-eureka: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka




